default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: vasa
  password: <%= ENV['PASSWORD'] %>
  database: beta_development

test:
  <<: *default
  username: vasa
  password: <%= ENV['PASSWORD'] %>
  database: beta_test

production:
  <<: *default
  database: beta_production