export const PLUS_ONE = "PLUS_ONE";
export const COLOR_WHITE_HEX = "#FFFFFF";
export const COLOR_LIGHT_GREY_HEX = "#D8D8D8";
export const COLOR_GREY_HEX = "#A6A8A8";

export const ActionTypes = {
  UPDATE_BG: "UPDATE_BG",
  UPDATE_LOGO: "UPDATE_LOGO",
  UPDATE_LOGO_SIZE: "UPDATE_LOGO_SIZE",
  UPDATE_TITLE: "UPDATE_TITLE",
  UPDATE_DESCRIPTION: "UPDATE_DESCRIPTION"
};
